"""add offer fields to students table

Revision ID: 049f51ffe618
Revises: 41d6f1af8e1f
Create Date: 2026-05-14 12:21:48.881797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049f51ffe618'
down_revision: Union[str, None] = '41d6f1af8e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('offer_company', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('offer_position', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('offer_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'offer_received_at')
    op.drop_column('students', 'offer_position')
    op.drop_column('students', 'offer_company')
    # ### end Alembic commands ###
