"""add notification_log table

Revision ID: 4413e3441ce0
Revises: a9147f941ebf
Create Date: 2026-05-14 12:40:33.310148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4413e3441ce0'
down_revision: Union[str, None] = 'a9147f941ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('notification_key', sa.String(length=255), nullable=False),
    sa.Column('sent_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'notification_type', 'notification_key', 'sent_date', name='uq_notification_dedup')
    )
    op.create_index(op.f('ix_notification_log_notification_type'), 'notification_log', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_log_sent_date'), 'notification_log', ['sent_date'], unique=False)
    op.create_index(op.f('ix_notification_log_student_id'), 'notification_log', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_student_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_sent_date'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_notification_type'), table_name='notification_log')
    op.drop_table('notification_log')
    # ### end Alembic commands ###
