"""add_stages_and_deadline_tables

Revision ID: 61c117a4ebf4
Revises: 62b06fe1e0eb
Create Date: 2026-05-12 17:07:26.607494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c117a4ebf4'
down_revision: Union[str, None] = '62b06fe1e0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('planned_duration_days IS NULL OR planned_duration_days > 0', name='ck_planned_duration_positive'),
    sa.CheckConstraint('stage_number > 0', name='ck_stage_number_positive'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_id', 'stage_number', name='uq_direction_stage_number')
    )
    op.create_index(op.f('ix_stages_direction_id'), 'stages', ['direction_id'], unique=False)
    op.create_table('student_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mentor_task', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'done', 'overdue', 'cancelled', name='task_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('task_order IS NULL OR task_order > 0', name='ck_task_order_positive'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_stage_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'active', 'done', 'skipped', name='stage_progress_status', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('planned_deadline', sa.Date(), nullable=True),
    sa.Column('mentor_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_at >= started_at', name='ck_student_stage_progress_dates'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'stage_id', name='uq_student_stage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_stage_progress')
    op.drop_table('student_tasks')
    op.drop_index(op.f('ix_stages_direction_id'), table_name='stages')
    op.drop_table('stages')
    # ### end Alembic commands ###
