"""Add registration domain models with integrity constraints

Revision ID: 62b06fe1e0eb
Revises: 
Create Date: 2026-05-11 18:15:43.411086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b06fe1e0eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directions_code'), 'directions', ['code'], unique=True)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_telegram_id'), 'mentors', ['telegram_id'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_telegram_id'), 'students', ['telegram_id'], unique=True)
    op.create_table('direction_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('order_index >= 0', name='ck_direction_stage_order_positive'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direction_id', 'id', name='uq_direction_stage_composite'),
    sa.UniqueConstraint('direction_id', 'order_index', name='uq_direction_stage_order')
    )
    op.create_index(op.f('ix_direction_stages_direction_id'), 'direction_stages', ['direction_id'], unique=False)
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('suggested_timezone', sa.String(length=50), nullable=True),
    sa.Column('used_by_student_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(code) >= 6 AND length(code) <= 20', name='ck_invite_code_length'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_codes_code'), 'invite_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invite_codes_direction_id'), 'invite_codes', ['direction_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_mentor_id'), 'invite_codes', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_invite_codes_used_by_student_id'), 'invite_codes', ['used_by_student_id'], unique=False)
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['direction_id', 'current_stage_id'], ['direction_stages.direction_id', 'direction_stages.id'], name='fk_student_progress_direction_stage', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'direction_id', name='uq_student_direction')
    )
    op.create_index(op.f('ix_student_progress_current_stage_id'), 'student_progress', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_student_progress_direction_id'), 'student_progress', ['direction_id'], unique=False)
    op.create_index(op.f('ix_student_progress_student_id'), 'student_progress', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_progress_student_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_direction_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_current_stage_id'), table_name='student_progress')
    op.drop_table('student_progress')
    op.drop_index(op.f('ix_invite_codes_used_by_student_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_mentor_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_direction_id'), table_name='invite_codes')
    op.drop_index(op.f('ix_invite_codes_code'), table_name='invite_codes')
    op.drop_table('invite_codes')
    op.drop_index(op.f('ix_direction_stages_direction_id'), table_name='direction_stages')
    op.drop_table('direction_stages')
    op.drop_index(op.f('ix_students_telegram_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_mentors_telegram_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_directions_code'), table_name='directions')
    op.drop_table('directions')
    # ### end Alembic commands ###
