"""add is_paused field to students table

Revision ID: a9147f941ebf
Revises: 049f51ffe618
Create Date: 2026-05-14 12:32:20.886981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9147f941ebf'
down_revision: Union[str, None] = '049f51ffe618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_paused', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_paused')
    # ### end Alembic commands ###
