"""Business logic services."""

from sputnik_offer_crm.services.mentor import (
    InviteCodeGenerationError,
    MentorNotFoundError,
    MentorService,
    NoActiveDirectionsError,
)
from sputnik_offer_crm.services.mentor_deadline import (
    DeadlineManagementError,
    InvalidDeadlineDateError,
    MentorDeadlineService,
    NoStagesFoundError,
    StageDeadlinePreview,
    StudentHasNoProgressError as DeadlineStudentHasNoProgressError,
    StudentNotFoundError as DeadlineStudentNotFoundError,
)
from sputnik_offer_crm.services.mentor_progress import (
    AlreadyOnFinalStageError,
    AlreadyOnThisStageError,
    ManualStageSelectionError,
    MentorProgressService,
    MoveToNextStageError,
    NextStageInfo,
    NextStageNotFoundError,
    StageNotFoundError,
    StageNotInDirectionError,
    StudentHasNoProgressError,
    StudentNotFoundError,
)
from sputnik_offer_crm.services.mentor_student import (
    MentorStudentService,
    StudentCardInfo,
    StudentSearchResult,
)
from sputnik_offer_crm.services.mentor_student_status import (
    MentorStudentStatusService,
    StudentAlreadyInactiveError,
    StudentNotFoundError as StatusStudentNotFoundError,
    StudentStatusManagementError,
)
from sputnik_offer_crm.services.mentor_offer_completion import (
    MentorOfferCompletionService,
    OfferCompletionError,
    OfferCompletionStudentNotFoundError,
    StudentAlreadyCompletedError,
    StudentInactiveError,
)
from sputnik_offer_crm.services.mentor_pause_resume import (
    MentorPauseResumeService,
    PauseResumeError,
    PauseResumeStudentNotFoundError,
    StudentAlreadyPausedError,
    StudentInactiveError as PauseResumeStudentInactiveError,
    StudentNotPausedError,
)
from sputnik_offer_crm.services.notification import (
    DeadlineReminder,
    NotificationRecipient,
    NotificationService,
    WeeklyReportReminder,
)
from sputnik_offer_crm.services.direction_management import (
    DirectionManagementService,
    DirectionManagementError,
    DirectionCodeAlreadyExistsError,
    DirectionNotFoundError,
    DirectionInUseError,
    DirectionStageNotFoundError,
    DirectionStageInUseError,
)
from sputnik_offer_crm.services.registration import (
    DirectionHasNoStagesError,
    InviteCodeAlreadyUsedError,
    InviteCodeNotFoundError,
    InviteCodeValidationError,
    RegistrationResult,
    RegistrationService,
)
from sputnik_offer_crm.services.student import (
    DeadlineInfo,
    StudentProgressInfo,
    StudentService,
)
from sputnik_offer_crm.services.weekly_report import WeeklyReportService

__all__ = [
    "RegistrationService",
    "RegistrationResult",
    "InviteCodeValidationError",
    "InviteCodeNotFoundError",
    "InviteCodeAlreadyUsedError",
    "DirectionHasNoStagesError",
    "MentorService",
    "MentorNotFoundError",
    "NoActiveDirectionsError",
    "InviteCodeGenerationError",
    "StudentService",
    "StudentProgressInfo",
    "DeadlineInfo",
    "WeeklyReportService",
    "MentorStudentService",
    "StudentSearchResult",
    "StudentCardInfo",
    "MentorProgressService",
    "NextStageInfo",
    "MoveToNextStageError",
    "StudentNotFoundError",
    "StudentHasNoProgressError",
    "AlreadyOnFinalStageError",
    "NextStageNotFoundError",
    "ManualStageSelectionError",
    "StageNotFoundError",
    "StageNotInDirectionError",
    "AlreadyOnThisStageError",
    "MentorDeadlineService",
    "DeadlineManagementError",
    "DeadlineStudentNotFoundError",
    "DeadlineStudentHasNoProgressError",
    "InvalidDeadlineDateError",
    "NoStagesFoundError",
    "StageDeadlinePreview",
    "MentorStudentStatusService",
    "StudentStatusManagementError",
    "StatusStudentNotFoundError",
    "StudentAlreadyInactiveError",
    "MentorOfferCompletionService",
    "OfferCompletionError",
    "OfferCompletionStudentNotFoundError",
    "StudentAlreadyCompletedError",
    "StudentInactiveError",
    "MentorPauseResumeService",
    "PauseResumeError",
    "PauseResumeStudentNotFoundError",
    "StudentAlreadyPausedError",
    "StudentNotPausedError",
    "PauseResumeStudentInactiveError",
    "NotificationService",
    "NotificationRecipient",
    "WeeklyReportReminder",
    "DeadlineReminder",
    "DirectionManagementService",
    "DirectionManagementError",
    "DirectionCodeAlreadyExistsError",
    "DirectionNotFoundError",
    "DirectionInUseError",
    "DirectionStageNotFoundError",
    "DirectionStageInUseError",
]
